### ISSUE TITLE
Better exception messages

### ISSUE THREAD

**Issue by mecha** [wp-oop/transient-cache#13]
The [exception that could be thrown when clearing the cache][1] provides no meaningful explanation as to why the clearing could have failed.

There are a few exceptions that this `catch` could catch, but most of them will most likely never happen during cache clearing (such as [this one][2] since the cache clearing process starts by retrieving keys from the database that _do_ start with the prefix).

Clearing errors will typically arise from an exception thrown in [`delete()`][3], which itself also catches and re-throws from [`deleteTransient()`][4].

Ideally, the actual error message is not lost when an exception is caught and re-thrown. This puts burden on consumers to iterate through the stack trace in hopes of finding the actual reason for a failure. That process alone is sketchy at best, as the consumer would need to somehow know how long they should recurse into the stack trace in order to obtain a meaningful error message.

---

**Suggestions:**

a. Do not catch and re-thrown exceptions wherever possible
b. Re-thrown exceptions re-use the inner exception's message
c. Re-thrown exceptions append the inner exception's message to their own 

[1]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePool.php#L168
[2]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePool.php#L582
[3]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePool.php#L151
[4]: https://github.com/wp-oop/transient-cache/blob/develop/src/CachePool.php#L361

**Comment by XedinUnknown** [comment]
> This puts burden on consumers to iterate through the stack trace in hopes of finding the actual reason for a failure. That process alone is sketchy at best, as the consumer would need to somehow know how long they should recurse into the stack trace in order to obtain a meaningful error message.

You are referring to _programmatic_ access to the inner exception with the meaningful message, right?

**Comment by mecha** [comment]
Yes, algorithmically trying to deduce which inner exception has the most meaningful message.

**Comment by mecha** [comment]
I have another case where the exception messages are misleading. This one in particular is causing us a lot of issues.

----

At seemingly random times, `CachePool::set()` seems to fail with the exception:

```
Could not write value for key "..." to cache
```

This exception is thrown [here](https://github.com/wp-oop/transient-cache/blob/49cb8258f71ddb4ebeb83dd80b4cdce20590cbef/src/CachePool.php#L131).

It's pretty evident that this is originating from the `setTransient()` method, seeing as how it's the only thing inside the `try..catch` block. The issue comes when we look deeper into that method.

The `setTransient()` method, can actually throw **two** different types of exceptions:
* [the one it throws itself](https://github.com/wp-oop/transient-cache/blob/49cb8258f71ddb4ebeb83dd80b4cdce20590cbef/src/CachePool.php#L312) (`RuntimeException`)
* [the one thrown by the `validateTransientKey()` call](https://github.com/wp-oop/transient-cache/blob/49cb8258f71ddb4ebeb83dd80b4cdce20590cbef/src/CachePool.php#L404) (`RangeException`)

The method originally in question, `CachePool::set()` catches `RuntimeException`, but will catch both of these (since `RangeException` extends `RuntimeException`). And in doing so it re-throws a completely new exception with a completely vague message.

And because we simply report these "soft" non-critical errors as a toast popup to the user, we have no idea which of the two exceptions is actually being thrown.

----

Expected a PR today :) These exceptions re-throws are getting out of hand.
